### ISSUE TITLE
Why is it not using full TCP for the forwarding?

### ISSUE THREAD

**Issue by Ten0** [Leayal/AmongUs-proxy#1] opened 2020-12-14 00:46 UTC
I like a lot the fact it forwards through TCP, so hopefully it will be way more reliable than the original full udp game, but unfortunately I can't make it work.

I'm trying to use this with two computers and two different steam accounts, and it seems to not work:
- A game appears in Among us, but it's listed with 0/10 players (regardless of whether the host has actually created a game)
- When you try to connect (regardless of whether the game was created) you get the following message:
````
Reliable packet 1 (size=12) was not ack'd after 7532ms (9 resends)
````

Aditionally, game does not show in the local server list on a mobile phone that's on the same network as the PC that runs the proxy, which should be the case if the proxy was properly simulating an among us client.

**Comment by Ten0** [comment] 2020-12-14 01:23
Oh ok so this is what happens when UDP is not forwarded. So I thought this was forwarding using full TCP, but in fact it's not, even though it seems part of it uses TCP.

So in the end I can make it work, which is nice, but at the same time I was really hyped about this tool because I thought it was forwarging in full TCP, which would mean hell of a lot less disconnects, and if I'm doing UDP anyway I don't know why I'd not rather use https://github.com/Tudor3510/Proxom that does not even require the server to run anything.

Why is this not using TCP anymore (or at least provide an option to choose between both), and why does my phone not see the forwarded server?

**Comment by Leayal** [comment] 2020-12-14 07:36
I'm sorry not clarify it well that the application will use both UDP and TCP.
I was planning to make all UDP packets to go through TCP tunnel as well.
However, I lack of experience to handle the case.
And as much as you can see, this whole thing is kinda spaghetti code.

I used TCP protocol for server broadcasting because the moment the proxy server breaks the connections or the client lost the connection to the proxy server, the proxy clients will immediately get EOF and I can use this as a signal to stop relaying the broadcast packets and game packets immediately. Though, I think because of this that it may be the cause of disconnections?

Also, I think is that if I redirected the UDP packets inside a TCP connection, it would lose the benefits that UDP offers from connectionless mechanism, which is what the has chosen for reason(s). On the other hand, if I handled the tunnel incorrectly, it would add lag or unstability.

As for why it's not properly working for mobile, I don't know how the game works on mobile. And I think the game on mobile uses other port numbers? But I've already mentioned that I have no intention to make it work on/for mobile.

Though, I'll fix the README.md to clarify it, sorry again.

P/s: I think it's best to let the game handle UDP packets with least additional factors (Eg: strict packet order from TCP, in case using TCP tunnel) as the game was designed to do so.

**Comment by Leayal** [comment] 2020-12-14 08:22
And I think [Proxom](https://github.com/Tudor3510/Proxom) is much better than mine in many aspects.
Lol

**Comment by Ten0** [comment] 2020-12-14 11:29
Originally written in your message before the edit:
> Unlike TCP, where the case is the connection stream is broken and it's forced to make another to keep going, UDP can just `forget previous packets and continue sending more regardless` (for client-side) or `not receive the loss packets and continue receiving more` (for server-side) without connection re-try mechanism.

It's worth noting that recovering includes TCP's ability to retry sending lost packets wayy before deciding that stream is broken and it has to make a new one, which in turn makes it way more stable.

> I think it's best to let the game handle UDP packets with least additional factors (Eg: strict packet order from TCP, in case using TCP tunnel) as the game was designed to do so.

I would probably think so too if not for the tens of times players have been randomly disconnected from the games due to "received old version settings", "packet not ack-ed", or if I didn't meet scenarios where some players would see another player dead, and some players would see him alive because the packet that mentioned he was dead happened to be lost, or that kind of stuff...
Indeed, strict packet order seems unnecessary, and if the game was properly handling lost packets, then I would agree with you. However, I'd rather suffer from a slightly increased latency and an unnecessary strict packet order requirement (that would probably be minimal suffering) rather than from all the previously mentioned issues.

> if I handled the tunnel incorrectly, it would add lag or unstability

But hopefully the software works eventually ^^

> And I think [Proxom](https://github.com/Tudor3510/Proxom) is much better than mine in many aspects.

But if your software provided a fix for the global instability of the game, then that would become very debatable.

**Comment by Ten0** [comment] 2020-12-14 11:30
> As for why it's not properly working for mobile, I don't know how the game works on mobile. And I think the game on mobile uses other port numbers? But I've already mentioned that I have no intention to make it work on/for mobile.

The idea would not be to make a mobile app, but just to make it so that if it's running on a PC on the same local network, mobile could also connect.
It looks like a change similar to this one would have to be made:
https://github.com/NickCis/among-us-proxy/commit/f81bee071ddbe94f5f9eea994564dbc1a5f3e826

**Comment by Leayal** [comment] 2020-12-14 12:00
Isn't the game `Local games` able to broadcast and discover hosted games on same local network by itself?

**Comment by Ten0** [comment] 2020-12-14 13:16
> Isn't the game `Local games` able to broadcast and discover hosted games on same local network by itself?

Scenario is:
 - PC1 Network1: Among us host & proxy in host mode
 - PC2 Network2: proxy in client mode
 - PC/Phone3 Network2: Among us client connecting to PC2's proxy

**Comment by Leayal** [comment] 2020-12-14 13:42
I see.
Actually, the proxy client on the PC3 should connect directly to the proxy server on PC1.
All proxy clients are supposed to connect to the proxy server directly, not peer-to-peer.

This means that the proxy client is required on the client's devices. If the third device is a mobile, I'm afraid the proxy can't help much.
Though I can try to write a redirector or p2p tunnel in that case, but it may be likely to become another non-user-friendly one.
Eg: Phone3->PC2->PC1.

**Comment by Ten0** [comment] 2020-12-14 13:47
> I see.
> Actually, the proxy client on the PC3 should connect directly to the proxy server on PC1.
> All proxy clients are supposed to connect to the proxy server directly, not peer-to-peer.

Note in my scenario there is no proxy client on PC3. But it could still work by doing something similar to commit mentioned in https://github.com/Leayal/AmongUs-proxy/issues/1#issuecomment-744378894

**Comment by Leayal** [comment] 2020-12-14 13:50
~~I'll try to make another mode for the GUI, which will form a redirect tunnel in this case, then.~~

**Comment by Ten0** [comment] 2020-12-14 14:01
I think the idea is to just broadcast on the whole local network.

**Comment by Leayal** [comment] 2020-12-14 14:22
I think I see what you mean now.
I will do that. 👍 
Sorry for wasting your time.

**Comment by Ten0** [comment] 2020-12-14 14:28
> I think I see what you mean now.
> I will do that. +1
> Sorry for wasting your time.

No problem, thanks for your tool and time <3

**Comment by Leayal** [comment] 2020-12-14 16:04
I've updated it.
I added the option to allow the proxy client broadcast the game to the whole local network or not.

~~It has a downside, though. You have to select the correct network interface (on proxy host's side). And `All Networks` just doesn't work.~~

Please test and see if it works for you.
I expect that it would have bugs.

If you encounter no bugs and this works for you, please close this issue.
As for the all packets through TCP, I'm afraid I can't do anything about it.

~~I think I will just remove the `All Networks` from the selection list since it won't work anymore anyway.~~
I made a mistake while testing on my end. That `All Networks` is still working fine.

**Comment by Leayal** [comment] 2020-12-31 04:37
Closed as no reply for more than 15 days.

**Closed as completed by Leayal** 2020-12-31 04:37 UTC
